name: conditional_check
on:
  workflow_dispatch:
    inputs:
      destination:
        type: choice
        description: Deploy to environment
        options:
        - dev
        - staging
        - prod
      obj_type:
        type: choice
        description: What object type to deploy
        default: Dashboard
        options: 
        - Dashboard
        - Look
        - Folder
      obj_recursive:
        type: boolean
        description: recursive (only for Folders)
        default: false
      folder_id:
        required: true
        type: string
        default: A
      obj_id1:
        required: true
        type: string
      obj_id2:
        required: false
        type: string
      obj_id3:
        required: false
        type: string
      obj_id4:
        required: false
        type: string
      obj_id5:
        required: false
        type: string
jobs:
  chk_folder:
    name: chk_folder
    runs-on: ubuntu-latest
    steps:
        - run: echo "this is " ${{ github.event.inputs.folder_id }}
        - id: set
          run: |
            echo "::set-output name=run_job_looker_deploy::${{ github.event.inputs.folder_id }}"
    outputs:
        run_job_looker_deploy: ${{ steps.set.outputs.run_job_looker_deploy }}
  looker_deploy:
    name: looker_deploy
    runs-on: ubuntu-latest
    needs:
      - chk_folder
    if: needs.chk_folder.outputs.run_job_looker_deploy == 'A'
    steps:
      - name: ldeploy
        run: echo "will deploy looker"
  deploy_status:
    name: deploy_status
    runs-on: ubuntu-latest
    needs:
      - chk_folder
      - looker_deploy
    if: |
      always() && 
      needs.looker_deploy.result == 'skipped'
    steps:
      - run: echo "You did not choose the right folder, please correct the input" 
      - run: exit 1
      
