name: Condition_Check_Git

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
   workflow_dispatch:
    inputs:
      obj_id1:
        required: true
        type: string
jobs:
  ram:
    runs-on: ubuntu-latest
    steps:
      - name: sample Job
        run: echo ram
      - name: echo secrets
        run: echo ${{ secrets.MY_FIRST_SECRET }}
      - name: echo INPUT
        run: echo ${{ github.event.inputs.obj_id1 }}
      - name: conditional_check_if
        if: ${{ github.event.inputs.obj_id1 }} in ( 'A', '1')
        run: exit 0
      - name: conditional_check_else
        if: ${{ github.event.inputs.obj_id1 }} not in ('A', '1')
        run: exit 1
