name: test
on:
  workflow_dispatch:
    inputs:
      obj_id1:
        required: true
        type: string
jobs:
  check_folder_true:
    name: check_folder_true
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ github.event.inputs.obj_id1 }}
      - id: set
        run: |
        if: ${{ github.event.inputs.obj_id1 }} == A
          echo "::set-output name=run_job_check_folder_false::yes"
    outputs:
      run_job_check_folder_false: ${{ steps.set.outputs.run_job_b }}
  check_folder_false:
    name: check_folder_false
    runs-on: ubuntu-latest
    needs:
      - check_folder_true
    if: needs.check_folder_false.outputs.run_job_check_folder_false == 'yes'
    steps:
      - run: |
        if: ${{ github.event.inputs.obj_id1 }} != A
          exit 1
  migrate:
    name: deploy_looker
    runs-on: ubuntu-latest
    needs:
      - check_folder_true
      - check_folder_false
    if: needs.check_folder_true.result == 'success' || needs.b.result == 'skipped'
    steps:
      - run: echo "C"
