name: conditional_check
on:
  workflow_dispatch:
    inputs:
      obj_id1:
        required: true
        type: string
jobs:
  a:
    name: a
    runs-on: ubuntu-latest
    steps:
        - run: echo "this is " ${{ github.event.inputs.obj_id1 }}
        - id: set
          run: |
            echo "::set-output name=run_job_b::${{ github.event.inputs.obj_id1 }}"
    outputs:
        run_job_b: ${{ steps.set.outputs.run_job_b }}
    
  b:
    name: b
    runs-on: ubuntu-latest
    needs:
      - a
    if: needs.a.outputs.run_job_b == 'B'
    steps:
      - run: |
          echo "will deploy looker"
  
      
