name: Condition_Check_Git

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
   workflow_dispatch:
jobs:
  ram:
    runs-on: ubuntu-latest
    steps:
      - name: sample Job
        run: echo ram
      - name: echo secrets
        run: echo ${{secrets.MY_FIRST_SECRET }}
