name: conditional_check
on:
  workflow_dispatch:
    inputs:
      obj_id1:
        required: true
        type: string
jobs:
  cond_yes:
    name: right_folder
    runs-on: ubuntu-latest
    steps:
      - id: set
        run: |
        if: ${{ github.event.inputs.obj_id1 }} == A
          echo "::set-output name=wrong_folder_job::yes"
    outputs:
      wrong_folder_job: ${{ steps.set.outputs.wrong_folder }}
  cond_no:
    name: incorrect_folder
    runs-on: ubuntu-latest
    needs:
      - cond_yes
    if: needs.cond_yes.outputs.wrong_folder == 'yes'
    steps:
      - run: |
          exit 1
