name: conditional_check
on:
  workflow_dispatch:
    inputs:
      obj_id1:
        required: true
        type: string
jobs:
  chk_folder:
    name: chk_folder
    runs-on: ubuntu-latest
    steps:
        - run: echo "this is " ${{ github.event.inputs.obj_id1 }}
        - id: set
          run: |
            echo "::set-output name=run_job_looker_deploy::${{ github.event.inputs.obj_id1 }}"
    outputs:
        run_job_looker_deploy: ${{ steps.set.outputs.run_job_looker_deploy }}
  looker_deploy:
    name: looker_deploy
    runs-on: ubuntu-latest
    needs:
      - chk_folder
    if: needs.chk_folder.outputs.run_job_looker_deploy == 'A'
    steps:
      - run: |
          echo "will deploy looker"
  deploy_status:
    name: deploy_status
    runs-on: ubuntu-latest
    needs:
      - chk_folder
      - looker_deploy
    if: |
      always() && 
      needs.chk_folder.result == 'success' && 
      (needs.looker_deploy.result == 'success' || needs.looker_deploy.result == 'skipped')
    steps:
      - run: exit 1
      
